import * as fs from "node:fs";
import * as path from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { registerResidentTools } from "./resident-tools.mjs";
import { createMcpAdapter } from "pi-mcp-adapter";

interface McpConfig {
	mcpServers: Record<string, {
		url: string;
		auth: "bearer";
		bearerToken: string;
		lifecycle: "eager";
	}>;
}

function argumentValue(name: string): string | undefined {
	for (let index = 2; index < process.argv.length; index++) {
		const argument = process.argv[index];
		if (argument === name) return process.argv[index + 1];
		if (argument?.startsWith(`${name}=`)) return argument.slice(name.length + 1);
	}
	return undefined;
}

function loadMcpConfig(): McpConfig {
	const rawPath = argumentValue("--resident-mcp-config");
	if (!rawPath) throw new Error("--resident-mcp-config is required");
	const configPath = path.resolve(rawPath);
	const config = JSON.parse(fs.readFileSync(configPath, "utf8")) as McpConfig;
	const aif = config.mcpServers?.aif;
	if (!aif || typeof aif.url !== "string" || typeof aif.bearerToken !== "string") {
		throw new Error(`invalid resident MCP config: ${configPath}`);
	}
	return config;
}

export default function residentChildExtension(pi: ExtensionAPI): void {
	pi.registerFlag("resident-mcp-config", {
		description: "Private MCP configuration generated by the resident supervisor",
		type: "string",
	});
	const stateDir = process.env.PI_RESIDENT_STATE_DIR;
	if (!stateDir) throw new Error("PI_RESIDENT_STATE_DIR is required");
	registerResidentTools(pi, stateDir);
	createMcpAdapter({ config: loadMcpConfig() })(pi);
}
